<?xml version="1.0"?>
<package format="2">
  <name>gazebo_random_actor</name>
  <version>0.0.0</version>
  <description>The gazebo_random_actor package</description>

  <maintainer email="giovannimasi@byteverse.it">Giovanni Masi</maintainer>

  <license>TODO</license>

  <author email="giovannimasi@byteverse.it">Giovanni Masi</author>

  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>gazebo_ros</build_depend>
  <build_depend>roscpp</build_depend>
  <build_export_depend>gazebo_ros</build_export_depend>
  <build_export_depend>roscpp</build_export_depend>
  <exec_depend>gazebo_ros</exec_depend>
  <exec_depend>roscpp</exec_depend>

  <export>

  </export>

</package>
