<?xml version="1.0"?>
<package format="2">
  <name>game_theory_sim</name>
  <version>0.0.0</version>
  <description>The game_theory_sim package</description>

  <maintainer email="giovannimasi@byteverse.it">Giovanni Masi</maintainer>
  <maintainer email="">Pierfilippo Orsini</maintainer>
  <maintainer email="">Federico Melizza</maintainer>
  <maintainer email="">Riccardo Landi</maintainer>
  <maintainer email="">Alessandro Salomone</maintainer>

  <license>TODO</license>

  <author email="giovannimasi@byteverse.it">Giovanni Masi</author>

  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>gazebo_ros</build_depend>
  <build_depend>geometry_msgs</build_depend>
  <build_depend>rospy</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_depend>turtlebot3_gazebo</build_depend>
  <build_export_depend>gazebo_ros</build_export_depend>
  <build_export_depend>geometry_msgs</build_export_depend>
  <build_export_depend>rospy</build_export_depend>
  <build_export_depend>std_msgs</build_export_depend>
  <build_export_depend>turtlebot3_gazebo</build_export_depend>
  <exec_depend>gazebo_ros</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>rospy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>turtlebot3_gazebo</exec_depend>

  <export>

  </export>

</package>
